name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  library-swift-latest:
    name: Library
    if: |
      !contains(github.event.head_commit.message, '[ci skip]') &&
      !contains(github.event.head_commit.message, '[ci skip test]') &&
      !contains(github.event.head_commit.message, '[ci skip library-swift-latest]')
    runs-on: macos-13
    timeout-minutes: 30
    strategy:
      matrix:
        config:
          - debug
          - release
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode 15.2
      run: sudo xcode-select -s /Applications/Xcode_15.2.app
    - name: Run test
      run: make test
