name: Test

on:
  push:
  pull_request:
    branches: [ main, swift-macros ]

jobs:
  test-macos:
    runs-on: macos-13
    steps:
    - name: Select Xcode 15.0
      run: sudo xcode-select -switch /Applications/Xcode_15.0.app
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test
      run: make test
